import type { Metadata } from "next";
import { FeaturePageTemplate, type FeaturePageData } from "../../../../components/FeaturePageTemplate";

export const metadata: Metadata = {
 title: "AI Template Generation | TheHookLab",
 description: "Configure how AI analyzes videos for your specific niche. Ensure outputs perfectly match your brand voice.",
};

const data: FeaturePageData = {
 breadcrumbs: [
 { label: "Features", href: "#" },
 { label: "AI Templates", href: "/features/ai-templates" },
 ],
 eyebrow: "FEATURE",
 title: "Tailored to Your Exact Niche.",
 description: "Describe your brand once, and let Gemini AI create custom analysis and concept generation instructions specifically for your business. Stop getting generic advice and start getting tailored strategies.",
 features: [
 {
 title: "Custom Analysis Parameters",
 description: "Tell the AI what to focus on when analyzing competitor videos.",
 items: [
 "Focus the AI on B2B messaging vs B2C emotional hooks",
 "Instruct the AI to ignore certain editing styles that don't fit your brand",
 "Specify your exact target demographic so the analysis is contextualized",
 ],
 },
 {
 title: "Tailored Concept Generation",
 description: "When generating new scripts, ensure they match your brand's unique tone.",
 items: [
 "Set your brand voice (e.g., authoritative, humorous, educational)",
 "Include mandatory call-to-actions or product mentions",
 "Specify constraints (e.g., 'we only shoot with iPhones, no studio lights')",
 ],
 },
 {
 title: "Auto-Generated by AI",
 description: "You don't need to be a prompt engineer to get great results.",
 items: [
 "Simply describe your business in plain English",
 "Our engine automatically builds a complex system prompt behind the scenes",
 "Save multiple templates for different brands or campaigns",
 ],
 },
 ],
 useCases: [
 {
 title: "Agency Client Management",
 description: "Create a unique AI template for each of your 10 clients. When you analyze a video, apply the specific client's template to get a script perfectly tailored for them.",
 },
 {
 title: "Maintaining Brand Guidelines",
 description: "Ensure that every concept generated by your team adheres to strict brand voice guidelines by baking them directly into the AI template.",
 },
 ],
 audiences: [
 {
 title: "Agencies & Freelancers",
 description: "Manage multiple disparate brand voices effortlessly with saved templates.",
 },
 {
 title: "Established Brands",
 description: "Ensure AI outputs never sound 'like AI' by heavily constraining the tone and formatting.",
 },
 ],
 faq: [
 {
 question: "How many templates can I save?",
 answer: "Starter plans include 3 templates. Growth plans include 10. Pro and Agency plans include unlimited templates.",
 },
 {
 question: "Do I need to know how to write prompts?",
 answer: "Not at all. You just describe your brand, your audience, and your goals. Our system formats it into a highly optimized prompt structure.",
 },
 ],
 relatedPages: [
 { label: "Deep Reel Analyzer", href: "/features/deep-reel-analyzer" },
 { label: "Content Mix Engine", href: "/features/content-mix" },
 ],
};

export default function AITemplatesPage() {
 return <FeaturePageTemplate data={data} />;
}
